# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Shresth Verma
tagline:          Journey to the Deep
description:      Adventures in Deep Learning and Neural Networks
url:              
baseurl:          

author:
  name:           'Shresth Verma'
  url:            https://github.com/vermashresth

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
